---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: svc-auth-secrets
  namespace: school-dev
spec:
  encryptedData:
    jwt-refresh-secret: AgCt1NJPCo2lDH2Df10/rd9qinyve8sgUTOGWpY7Z5tsrfqe6xyLxD50je52Jyce0mBkpxEwTh5sEDycXaEd3SGnVnWWHCDHkcrHUVpPa28K5bNmr4+jc107SXgiCdBsI5oUbLPKX1INCY9NzIot9X0DnJ0RrYellHjkiA5bjlKyJZxF75gIBHIjXm+oFk95LI0RQIPGmju+qP/rsjj7W3BNIqKkvFGjYZ84wOwjGote4E8S0aaRCdg0X4qta/yPZycoIARy2/G4FSjve8iXpJVUh8VSqrwFqn7g3MtNq+2zHDt8rm3s+rsR/83rU1figNg4sFRxyDKfCnUJ0JvKN7j4q6/K3nV7MBx++YqMo1XheRpa4jpQWyhGwAJMp0L7Yc4B6OvGqMaLmD37CboycWXd3yXn0MH3PjF6hDSFK3WhXctKpkGMQw+BUFDulqGQFJ+CiMHUsNXEyHHFUjLL7P1+4lFmb//Sv5HxJr2h3hzjmPXYlQ9KGSgYbT67TC7Ceq2YZGX4yxAYoFnWsDGxXG15DdljItmcsB65ckqjfIzwchlE8FFuEkljEN2VtKv3YR/IN2kjYJvfnVNwJIysGktSXSN2B8Vobruv4w3JUty/xlam3im7VReBZOZ4xwVH/ubi2DVZP/euiHDeILi4yr5HQRSCTFtxMRVD50DK3XIyDeNkR1kuK9qsTl9NuM6GCyiaBMhIvKRNWIV21GtGWC1MqFWZycSW/qpD9lVlBNbhMQk0FANaTwFhCVHZlOAO5qfESo+Pe7W170h8BYyEJfdAqyWIYPNQe1XLCmCD65Lae5NjcRtfZyPY/g==
    jwt-secret: AgCDCLnKNLJCaTWpAte+TFIB/QgkKb4XrqPxbRYOcDkuYYwqJBGSpMxWUmnIiSXFPfdWjHX/uEdaFiTQhGK3Xm4nJrfCEHUli7zd3gZ1/00p3eJwz6ew3ydGLP+q9F0DjNuI6YtIgI9ZVBLfQ2p94ak4VWITCcqvbmi+L/H2gJa+WNEeZAYQ+afPU3qtKhD901VffAdH0Ds73EJQST0ZlRmUyOXsv5+F+EtCdLP1MbwkIQ0mUimcKFlfz2ksf1yWplrfFla83ec/p18NUfvQWNMeG2Fe+8Lifh3LPuLFwODgSVWxwUbl+eavJtS+fJ0FKzRVtVy/WPV08UsjouwKLkLgL1iVUr1z+hS0WhLiF+4meZLl2QSjnYi0/r1dShh2rVokPdrqqzv4gG2Sy68avVzHoOn57n2PhCdZQFXXU85bySpeyQid9Q6WvuXISNFfs0tz3k6srrGFtTgKdDKJ9O/Yzi8NW9G23Nn3aASk2HwMHL0aBN1pqoENMlYFzr0aQTGbO9yVuq2XBmG8GLngBU8/ZBo5fggSLkmzOYFA2t5FA7j42J8GKZ9NXEkJmB63MBxKvLoyKyuLdQpkK3NeTqFk0GL80lgG6NFr8xVvBwtNKz7MKImFY6dR9WN2w51Vc65kBSCiABh07yJvJ69RKQ6t6LAy958ozQA2FKAcZOHJDmTXgMTeF77RUnqcqcb9H0BZzazaT4FWI8XsURFzL4iEkvOCxaF6CE5MMbG4aFcEZqE47tS23PLenyFtjLPgvYl9YePVXS8szrCAnq1moyhns5up/6veYitqwdDOUGpNHmxTfj/9Um+ENA==
  template:
    metadata:
      creationTimestamp: null
      name: svc-auth-secrets
      namespace: school-dev
