apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: school-postgres
  namespace: shared
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"

  bootstrap:
    initdb:
      database: school
      owner: school_admin
      secret:
        name: school-postgres-credentials

  storage:
    storageClass: local-path
    size: 5Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
