---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: school-postgres-credentials
  namespace: shared
spec:
  encryptedData:
    password: AgBy40xs0OOiMISsiM1rh36KuUGZCsluYz7Hj6uDJSGyqdJ3xL1lztfAsko/zVydoYfHSGtGDtNqx0zl8zKh4gkHzlCipIu/eqJt7xIL8v1uxpMfIhcH+wAtjke7ab9FxLlF2ka35N9tuDXFWyY3x3QO0rvyjOyHX1+QkrvHFDdXzDu+6ASgbiMjukpvJCywE9sqCfDcmUqhp4hIZ6VUNNhC4/MhC88lDpovxvEzz5uWxJlqCtO4f1mu3ceFviBq8o3UUeumCtlPBCK9Dm253XnpwikbMh/XpaXTfhBkPNCxbL/R2p/qIkSFbaOsjA22U6m3RlCPRy5DAVA7Hf+qXd/VmF9dgUW7jsx4IENofZgRUxLXVCdiGjpAkGO1b8WmSEGRAOw3EghWR8X+W6Tbcdzchg0LYn7G8SkKPp6cZsEXezShGSCJAhh8tSrwOC8OsBiiRfkf13A87UsG9Fg4ZfIF6daSFX6cpBz/XA9CFIhNViRKNYczzKXugdLG1jbDDLg1Gwjhk9K6qWj9Tnfws+enN91esszO/bFZIO9byrez2w2PZ8KpAMlWOGLiGMQk9+4XAhZHghU6JBImO9KF7TX3tT9JzoC69z09EUgKYvfYsw9Rf/WFpHF3dimUPlSHsV6JP0F6lecJ3bMh2tfDmgEvAMx2oARmBW9e2jZVG9tOTzVnyCZdTwpv0fvWCj48xzdIlxWETTdbtkKVH9w7UA==
    username: AgAvDBaBxpfnCFLLFUM8Y1M15ftubkwkOJh/iVi0A6OkBl10z01yiderMX6wk4LuD48MdtGuE8mRdmG16gn5NofjeoV59tzFa5jAyDgGy8X2zN9kfGvbzprm/RsYDV1/PZMmfw6tuPEYEYl/9OsbNJTDKfZh1TzqOF5ekjFBPLuPLbhABln6eBCAgCeembY5ryqkfVuDA0yi47JBUEV7LYJW5DGrKhPOgUWmD28Yp7E38j9tVLDvZWcf/LqWPRowdb8UQX2y1YScm3RR1o92LlRdfBAzHQTh/9ff4kRvozvBzJySCazDXWFGITIZ6b7ASvM7B7CzqUBiIiJP7CEQZvCXaKkjzqc999PguJvDYQ3FGcYqNchKTRiw/RsPZV5QaigWQhLEroo3C95wciI2vx1K7JSCuUhVK05YtgxE+X+M1lNWnLHU9oaUwx5Lw+i9Hzc7X+lLrOhJjZRi/i6zgZBAKH7VSE8DvRn9+Qz6Lvic5tE5xd4QamQxRHhpVBLk76pnYMV+82HtQMmgPWq0nUVYCSb4cHHNf4Uaz4fZMnoUbW7LsvlzxCej02rA3l5Fqh8Ejef8vuyhY0Fnhz6Jialm8ci8VgJaeEBCwSbOKIvSKhpQ1jVatNdfQGu3CZ7/Y1o+mnV1ngxu/hDF9aNyDt9/Nu+fPrHnyCZptOLOiEsPBrA0EafqKb8B4vNofznbS/yMf2uwTPuOywF70A4=
  template:
    metadata:
      creationTimestamp: null
      name: school-postgres-credentials
      namespace: shared
