apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-omnibus-data
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      # 50Gi for git repos + 10Gi for app state (logs, tmp, uploads before MinIO push)
      storage: 60Gi
