apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-postgres
  namespace: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: gitlabhq_production
      owner: app
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_trgm;
        - CREATE EXTENSION IF NOT EXISTS btree_gist;

  storage:
    storageClass: local-path
    size: 10Gi

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  affinity:
    nodeSelector:
      kubernetes.io/hostname: pi-node-03

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi
