---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-registry-storage
  namespace: gitlab
spec:
  encryptedData:
    config: AgAOVovYqJhOu5uSpS1DXuS2H9RAmBN6VgLwOEYUSa3649aNaSEaSCjjnIV+p21aU/5G94wRr8+p+4gJ/VsQdMxNZflvH5dTHNXCTBtVE13dZyLoyTwJAZrY9guvxv7T1pDezr31/5TWQqwhHrQ878jWN3LJ3kWojKeNEaj3ijx4EdrHao5Bz0HArj8So0Jc2RwZCa5Q0rZgAhXYA5o9sCzDdM4ASZuYKNvuzZ8fNz7AyrTv1sZ8eIzwzIxGhZoZdg/LaoGeAm4stfRQpdLl4TZ/fVrSx1nTywcbKZgcpcLy9yNCNSABsKkFICcgNqJH7dn39igU9lsbeHoGFAp0ucqc4lL0boGRVpFDJqLQE5/oxpcqMMBT16HMOZW1sUpzDy2WZGmLxYouLc0J09rE7uy7U+n5b5aIXkmhqN4pDsf7KkyImeP7QHfHCRiXnKbVMN45dIE78Bx0kijN7oghrY++GWNM27RFyJB5jS9p00oE+DGmvkTCBCRShxW/gnlnbBmThJ9rpDkC7WPp2Mw+r6g/JiGs+chaTwYpxB+n0VRk+u5yTHAk1WHMnYv/EXS5fjptFhmlsNwhlOwNpiYaDKoRdGF/OSMaH1AOtpWG9UfdvnKBPitz801DKAz+jnfOExozgiqh6mUhcg4g1YRFw4NpT7rC0LOI90wQEqKAuhoQnjczKC1vz+6yADO4CowpSjr15SbB//6SnQJqFvtENQ4xQfZMtgx6vOM3jghGbBsTQ7JZKSvEr33J+lPp/Yu8piKtzgNNrAZ/DmFIx11cQqpgeOTVYzmZIULi+vYCASmfZYSPjihTqx+au081wNfm7CPKg1ZfNX+UL/y5KvV7COLtUJyThNHeW9rjCLH8bUKNWJ6mP8DkuDlmiVgyh0K3TnP1SzqIg2EUhGCdmjGkO0UfTIbHIyNP6j736DR65BUIas6lWexz+YvSiLQyeQofaXA02gNfWK9GbmDrqX0n
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-registry-storage
      namespace: gitlab
