---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-minio-connection
  namespace: gitlab
spec:
  encryptedData:
    connection: AgCl8PHR1I+7kTsgeI11keAWTGyVEr1N73gqP96MWmsFuZW+AlwsuPicuJ0fzjth++wMaie58jGcxo7j1M4G+SBwgjY5Mr91mnXUNhHG6OkvPKfdNgXNajkLUALo9aLMdJikpZv6IYKvo9+Xrd66l5BeQUHN5Wpehw5b9wfNZx5wEVy3NI1SLexsNC5R8HR3oT8rEBtv5CkElGWl2HdeDPVGfg7W6QTHuj08LlyRWShd+AzxV07OtxnmdHHiEIf12r803bYRHkhHwuIrwTkP/VM7m89yUDp3b76c6JQoq3ExENYn7Vkdcn7ETbZ7hW5SIDKL827en1TOsl98sWfTabXRIaq+mAu30LB1GtGWYHO+VgSc42HyBljxu6wwbVkDvBxajr7fF/U9WasUG/boOGW8NUz+kvlxuBV4p4gSIFtvX5LIVn+2y880/ucp+iFTIC1YJhZR7S2QiIQKqiePBOqKh6+VKsfRektWbvUuA0jqB+rDIj1kfKfPtSpHw9zo/dAgx3Y6aXg7hFWLltkNMDO83HIXj8TP/IJqa5d0t4371BnjPomh8541ivd/DI7dYjLF8IqfPkyIoerMDgsURINl+vjprnZXuOtYr4ttcXM8nMQciFlI8cyI6puhT1wK/R+M/7TQEBbXHhSXnK9ryyIe/vXKR70RjbRhrfWiYg/J/If71PGt2HVg/OUUwAcKAFy0XMxPsfjT9mBphEqoiOaMfkk6dhxWy3zptzpxDNYLH2lC6NbPDFs+vKZpZYAZGmcs0KKuVuvBFDCld2G5DTGppBl+0DcMZStDsy9x5l8ioXEoYHmTNVC1W978IjBsrDHWmbjeH9dtwez+naxvZZ7slk/Hqc2KMBq3lh0tuj96nSOpyaPUOu3Wu55RyJhrJICYHENie8xDncD8vJaqqiY73Lcptm826L0FY9qTdJO7Kz+JgVP3C5cAWzdT9qvTDJEirrwETdCDJ3V5YuHHyNHCGHve9FIj6aC/ugrRF7zbMKAdxi/YDAcj6qYITiukuke7XCziHbEwFA==
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-minio-connection
      namespace: gitlab
