---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-initial-root-password
  namespace: gitlab
spec:
  encryptedData:
    password: AgBLMjxy3+dSdxp0UHUep9fdLMyGLy4iqWum2J+al+uv2FxLcnIO5RG5KtRlc6DXL+bWc0iF1dL9IxexrK0fuqER0qrcToNq7pwVMg+hEu7/x09YiV9LHUhzBygC7295TzcwGoJE9lAaGpzDQzEM56e7k2/99SCbEQnc/oeBpLzf0a5S059NrlGPnDJ1KMIgbxflI12pawqbGv43e7Uo5aZB8qmQysl9oj8yiPm/f5vKb2kzcsIvw+SCZF8ZM7QnlSiiU6jy/Uf6In1AhtArmiSnBLoPlpcqJjWWBpyqVc2XIrG/vltjYLTiF94S14qQx6PDrY4dL0WEu1h0U9BOk89E59nvy+E8vjmSmlZXrHyDCuYa/AaQDEO0SfUqvfMer2CKTQzvd4Xuwm9Xh95kMz9SmpT3xanMMA6hr6aNx77f+A8mviLR1J3fvkVoHp18VtCVh9kywfBQ7VlidbgxGBcGk+0lzuMij86cnvx37z6v0K3/0HotA0YmrDvHCmjFaixb6LKpcayBJCnVqn9FtliZGJdfJjbKjaTQGT3t6aLoEXaJe1phrXVptvsi1ZK37Ca/z8czaYAON8RqjK71GsAXyWJPuBPaUitZLJpOxvjQNb5wcoAnFrQPzMMa7QLdxQxCi0vCytQw8aLEwMlc9tI74dbgvzIpHGIPCS5UWY6V6yCZvG5z90NXqaUUd5br8GPaLVt8Kl2D1SXpeylKe0wILj0yKw==
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-initial-root-password
      namespace: gitlab
