---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: school-redis-credentials
  namespace: gitlab
spec:
  encryptedData:
    redis-password: AgCTCRCfX5JxFB57XO+w0orpmXwB+PIJLMpMNj9BM8Yin8GZ48LCG2v31HJJO5vzqQ3SP75p3EsyoKPOSF5k29uLJtBopa4PrySmApvM85gcQtLW8kRHN+tly19AQ43i3NAfLi9btaBrp/HAV0IP6WR0vf9KMpoct0pjvt+YQeM6XvuZ2kViyMhFC6uOt1sVvAGj2HSCnOF2C36barzZX/kKGWnhJETnBCqbXq103fH3ZHwC8sFOdHNPPXpVcIeiIPh5Tz+cr/RaEfU4WIvLkh2IVWInQkdAB3BVIV6zc/vnlFOri4m31UOeKUM8fUjQxmEx2XSMLhdzTMrsccP879l5qxWJ8STBn3j6117yzMga2UU4tgQl2+xz2YyIDh5net+jSRju2PMtImu0MduvFkCkeGIEa7f2L9a8lDCRSj49W2AF04BXWQMfgWCnj342Uw9Elf2Cle16DlGrrShjJ3gJh6Bglt+jS5l95W2FG4NrcRqwTdD6WZy+gRfEL4D6AsAEyebSTSxzC8tcNDUY/UEzurynveaFwKZsVLhRuYjZ14F2GLdMHOaBNmbnCAlQ18AVHiCsDao9tVIoCfXWBz9R0yNaw0oilQY+Ruyn2tftCo1mux0t+yg8xTTGmu4ixNsgVy0yjs88hcD2KZaEq03oZ+p64tj+W08w4IAl2DX6RqxE5eewq4ax6n+y1NCmnazYRKW6v99DsNMh/0pT8A==
  template:
    metadata:
      creationTimestamp: null
      name: school-redis-credentials
      namespace: gitlab
