---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAmJvm9ey1lNMtejHfLKfvBmXQvlvJoGFfqMnlQiur0FA5tC3oe0O/1Y+7Z4gNDWM5EZjgWQTjS6jOK3ICSSJthp9FE62sFrO8DhQT933bOkzOARN+7hTA+k03za8nHB21baJAuFlSKY++3VxXOE1vw0823omcLrZmYxEGz71UpB5PMYdHnU3g8vys92FlG72QiBwjhyaJLKQEGh9ONiyLqwcWxmfibzItOlsPcKouM+vNAWXga7IETJF+RjuRFHs9PIodVJtkyMFWzOPNKqGYeHpoFacdf32uhHILaMFEj2SMRsd22Ql3Pv//MNTCoj3xgscEZLmpaUwZcr0IidA8565vNNpeqTGtHK1liKPaIREvVCD7c3Aa1lF7Rlq+aY6LpxV9CdhUOCsOBembTNyFW72Vx4krUkygaqodZjQe/idd3NBeAA/AtYEmcpVLieJrx4yLf+SMkL5avbJmPr71/RKj2RrO9/tKaM0AgW3n/plWexOm2gYO9TuHhoGcmQDC5Z3xnL3yIYkUm67hXjryuI9xOxU67HeCwHuCdtdKKn/BMva2YMJAYFJI70QJ9bJnWnZdRPnbJVT+fto3eKTvpMls1ZOseAOUtNEAWB4KT+peV6IOMoEwYdsepHui3XGR6ZHaeNOJllRjy3BHz/lfEED9gJ7Xmez4goaj/Jh+V2/AfZI5ISvBKnBDeluVKH2XKapGRiQQZE3Yr8YHD3OYXoPJvE8veeGTBJa+QCtG1HA==
    admin-user: AgA9WOKY/MEwfN3aza5xWJEMgwG+1GIZ9Zji6DuLx/mXk8dDX+FHUJ8AdtBIqGeaB4W5GRP3FZpa2Dou6CXbTEbwpXUoCKL7Zztc9nSdkUyb4d0ZeFya0kRsGI84J1M9PVMjYuBpKRPnLd5FlT4hGavBAg74mrTv2AIee+NlREaxqmtylNOfku7aFFfHrV+DFXt8WEeuB2xEFMZkGSNBRMnd0bpLDbYlRgsGIdoYuDl3Nigt4qFF8y175mtmJUJ2FdcuWncHp1/Vzcg7ITLNGdju+h887wggGRlTWSlWHMi6FQlvSUgFYy+al3lvfxs/GmKkXm6LVJZhvZ+dKPEA0O1JqRHzkKFmcDmfQzRPSx6Ou5EaGSjAYo69JeBGPjh3yxQk6b0xvNukCdvbXiENOGCc+ur49QHcApXGwwyVjjXmBlV4ZnKoL0G187RXbNXgHAH9LjGGqcDxksadL9kc8dg4AXYfD66yFai1E8xQ4eIp/HSinrMxK3eXtER7KXB7Tdjcxnx5oCipACg2uj7PJVQ7T3Gh4o0fEu8gVxgnjcEeYYpvkG3EcOc3je44Se5PTkvvV4B2j2CWuVi17wLdxAJaZ90on8TYUt9vLnN05ImK/fO5Gdyf1a/C7ZM4RmNA9QhBV5gw9FxEBBNsJL9P4eBzd9MoWePnpCMNMGU3q9V59q8e1Nt5lq7/vfWYx3ijOXbSJq7Tbg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
