---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: school-redis-credentials
  namespace: shared
spec:
  encryptedData:
    redis-password: AgAInugbEE/oz0h96cwKQMGZRsjjx4OB2CBagRDcYYqFZLm2M5TN//RYG8afIQAwYYiFTImjMEa0/4eLNZQrAw8ArY/WVZYgV2uiTZ7n+JXklc41p3MGuz2yMmK4mwnw82gATDUN4ybpjNXHS0dZB0VMg8m66Xg/eTHNvVAeGrmLeTzPxbjUnMqcIWyIiLWLcs63zc3WBzdItWSkU6visRZUOARQLBKRU7+8VcFFlmlKQZaOwvKzvwDXqTwFGIgHc9VoTB35/PYrI+FMjVeFRHGL/Ox/vn4+c0xmTzk5QoIXZvtRtYVrmsLQmrv6b0/CmwsLjJeaUz/cOfPmp6T3B+pzMYbY3FPNV2+kfKpJh7VoqhUc1ammmf0a3TQE4XjIC05FwN2ysgUXKP2drJ+gW9zCp3TVtV7/hbdp4I/MXMrimLcDzCO8MtWlzJSEUrj1CLj778PCVBdSVWh8ng9CMy41SNb2bhfjiHe46srYUPm9KGrqEKUaPwDECr+hvJcXqQ2/VUXS2WhrfEJJypyj7CTvW/6BKTnnVJcNhl6WmdBaNVIvX/A5VqtZRsLAyDg4Pm326piDGcHi/NGn2dJHH03bLeY5eKROWAiVOs/SdDfGARX+tkwHTvgi2LUiafsBzuPgS8W+DVN2VZPHhqHNQVqt8WRVgKLA6HG8ca/cxGU3wCjbcz/PWebK8WX1qYFSTE3+R/afthJtUzNUPyXOcg==
  template:
    metadata:
      creationTimestamp: null
      name: school-redis-credentials
      namespace: shared
