---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA7CUaWTPYZAUxRdXSJWwYafuDuXsUbH3sMwqzhB5vWslQkB3vxGbs4SHoSWr6zR7tbs/EmlX6B9Yci6XuiyjIa29FGFrFMopBEm6KDJVKebOZ2KKEbzoO5UB+HFaj4TQ7z9fPnpDbKBi+w5t/b5WerezJzUHMkmjZPy2ZohLRXRG+nqj2rhjMRzO2aObcS15qRzU04PhezKIorFqWLiqrRs7WazDNPNx/IuITv6UB5vfKUSwaH6hGlnD8S/abGtTIgeIQS3WRlXEchQu644YflJponRPbUzvmWhZyAdb4HqAq50gWPs/XCREwfAcuCjnpFxJoLKdRVwxbUav+OhR+TB4OpvjSFzPYsZ7Q4v9C+RieLEE3oSMpQu3t1FOU5dEREspn1RYC0EcqolxBO63/RdG2M1Z7qTvV28Zpcaa0OX5uRQI0G0udmkIn1tmAPiwv2U+kAXz7Vk1WmEG5Z252JZLlnxm1lMFtbFUVH7/6XBoPcxHwyAe1DNWWOtT6zmPoVX/u4CmMKUU6psil4TZx5hM2vQzfj1D4yL3ABuB2TinHZPqZe68Q+QSv8MhLKr9w8UHvETnRU1/dRy2sBHH8SvRbKFhNES8I02LbitUaA/tLBDj0CYJVzQOg3b6PTCtlx64i2Gi797XhJo8RXuYpP9W/EsW6vyJ2KgVMV/IKlK4mWfZUyQm9kGbbIPawUpIiVPM9r1yCKlEc1kjtEZnYbAt2B66Sxs+gIkPCFBrvkFg==
    admin-user: AgAWXs0gYm0Oce0a5TmGvtOWlImAHsdw7V+bZXRFfLP7HNSzYcJS0eIeRWU//pDhEs5X5ne2uTrNqXlEGOY67kFUuWBwet0UxxCt316ehldOBL9T/OEzhj8BmGHiAO0Un6Sa14+kT5a9Camh8pM5J3mZoPofrbksrfCHAmfLNRCUpd+GjMya6p5zuSfzjNWR0SiGoGb4SMH2k8N4z/oM3XtEal04gRTVjcZOIdsSO6d7J/tyKGEfCNYvKTJ8GuQovLJC+UgDZ3C0kMbCs8jv+CTnaRZKAd7NrGvRirTVQEE91pqPFRnIsVHKfZGvQb3Bv2MHJz0vg3iI7Atq+JVSoKpWFa2y1VcXT64cYyU3WRnFl8iBXqQte1WlrgLtHmC9CTP8Z0Og1WCmXhuLNfMI4FqHeLx6apQDVpctd9yGNxqjoomYvxOVUGQAiYjD9dkHJWQ/bzfPgv3QtL5rKSkujFCQq/c/FHUT8fT5/ydjunozhSNEJxkiFKrmh9R8TUCzEDRO4ldt/3li6yKtP9282N23MvDH0AvYwDUSlrv6xrBJcM13DDeZLoAu4CX8mScjBnMAN8+Sc7w2Sz5+MB36PCevNT/nEPHMuYd8NmbxFdmfFqjbHi0ZbUkJ8K9O/epkhJxwsO+9baessIN360HCDmwouywvmxLKmBLEZRHRJuYq7pOtLj4fEZ92bpycFZcdrTEkJUnJtA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
