apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  sources: # <--- Multi-sources
    # Source 1 : Le code de Prometheus (Helm)
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 56.21.3
      helm:
        valueFiles:
          - $values/grafana/values.yaml
    
    # Source 2 : Ton repo Git (pour les réglages)
    - repoURL: https://github.com/inforedaster/argocd-pi5.git
      targetRevision: HEAD
      ref: values # <--- On définit l'alias "$values"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
