apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/inforedaster/argocd-pi5.git
    targetRevision: HEAD
    path: sealed-secrets
    directory:
      exclude: "pub-sealed-secrets.pem"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
