---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: school-minio-credentials
  namespace: shared
spec:
  encryptedData:
    rootPassword: AgCECL0QfCWSMfUIGZsnKKNNMgsdtGeUCR/1+kZhu2+SPfx5roOLWj6I71dXE8dXYnQpSVtOajLh5mD2HtdoDY+MEJiMnnl8hd1Aq4M4Ne9j9iofEYIp5tEPLmn188KODHzgGERKYrkonXAFFE8GOnQeasX71fdrI21wyHJU1Jlmh7gfvTBRBOBs55VdH7+e3GDrfx6CmP3eqdgxFWAksynUyEUflUBwo77cZ3RfMwwoEQwffFA56HBgSc6jlkJ6LywRCNrUIGNietYOXVy6AB2iDQtAZKxzSk6dZwLOG+9UUMFO43Q1YIKyuxUM+B9PSUuiEohA9DJsc6Oe1DW3854gfzmbgS0/k+bSuHkWkaP8W/SZlOOKm8mxCkkK2BTHM9s70nUajDYH9EA0rxnvNE3gBoCcaW5Iwv3u7YerSpuG1yKpNhfXvaVqtJ0KboDajmk9Oi7n00+hdCTaRY3QozhLcWXE1SA1Sm0rM6rdk3q1KA7fPZGFWSR1MqyBzSCTFNhqhJZQ7HvW1Ng7grKo2ybH3Fq8qgaJc1BkCLrWYL8WXIKp9hI1/y70dZCrKEB9jt2/oJEyuFvvgsAd2E+rVsjQ7MOTr/GxfBN4sGJD76RCSrLj99FTrECYgcG/dJeLmoQC0cO3U0KOgyFwEsO8goZQ/0J7R6g5VTlkB51YALZ+6EiIbre4nUkFX7rK2n1SR+adjFB7QeHbRh0yO4Tp6Q==
    rootUser: AgBStkervcz0yd8UPHHS7IHqTOkzPiCDxfHUyWmL2Icwk2BN9qsABpTOIQL5jPp61d0Q9FiGz3JZNsvyZcyR5sJtKQNujeZxY4OcFtAhWxk+M1kl3oitsRS42/t0Q45cqhIShBKY5LCcAw7xzhvjRbG7GKZ2Iz5/vXn+usRt+Sk+C7MPe8zCvpKrax1bGmn0/xvnfKAzpWsTMB0BMur7sF0Hc1xsAP7Ie5/w14l70wRnax/EMrFgJwZfcIZE5vd+hX0mh0AWJti3J0HN/B/n2VRCxRwT1F6YWeGOnwZglz7fWdrGwB6R8kUSQHUOK5oX69c9nFeg9T16PhWH2dNY5GSNe65Af9np/DvAEL7YKAJqsmPsv4tc8kHmdZLktq0cvargtDLKoqyYXH+G2kNZnDVW1PhoNTAvOEMxAsMT5nKcTzt41zZQzC+v45M7dr14piHXfessdbFuM1NuKc7T8rLJM933HdZshpo52SgcS24xqFXtjeGVPO56hrsFdk1m381/2yxOA3J0LLUNKHqwZyygGuPuXL9g2thqI2rcSZ+NEL2wyT2aGa18B43s5E13zDnH4oEkUzNn6zV2WQ1JE5me4XSspJTEsm6OnevS6XUW+5MPEb/11KcGCVhpSCga+HrKTELzfGliXlnRP4hawCd+BzsOW33sw8fmF1p/zOQ+FNgFbA6A7OIm9Pb6rIfrnnKMdt0pR7t12oRqqQM=
  template:
    metadata:
      creationTimestamp: null
      name: school-minio-credentials
      namespace: shared
