---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-registry
  namespace: school-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCrrOvOcqW5eDUqlUqCe93Olqv8IVwEGpTmUCyWczQRO/dd0Qf5Fmd93/kXkk1kHcRP/MyScOzM8Yf/Vs4Ukc9HThs00Wd0XK3Y/fjeixJkhU+7qwkxWpY5tukV/9mcgpr0AOkN9NLeQA2UIlgbRGhPMYoRDIvvhfyo4XcbH3wuIAEK1FUqF1BdRb+9KVF4NIrjkNwbSTEEgmqzK6Oo7a9UsiVO3CacWmxv+s10NmCCj70KBlvaU3UhuAXM8X+vA+DhNtuvnCQC9NUY3HoNUxaJb/wxNe6L6uSSmQsQ6Km1v9bpj7dqY9O/Y9lzkCzxoM3ZAlwnuiD5/90ZpqEW8i5AascpwVia3Szc3H9YdB960BYypk3dDOrDfyqMMq5lQ/UHZ7uYMillU7+yzWHxj2F+RW+uEJ+gCRQyC1658dJcG6Q+Jx6/xb5F2BOnkqbADAcADiF8dwkVF5obhK9bJnLuaXYo1Lz8gHrMR5GSGZ+D/Hs6nwAaEJsWnjE4OUgPBLhv8TqcQu85zWOTNdXqPVPynMgpwebuM03g75Giu0y+0iMgR/eCnaeS53gp/3biF3eQ1OX3C41V86dTBgVwHceIqrn/2TKBQ4fmVuCMA/saINLrDYcB9/ykaC92xtNOhnBGRMYXgTrOmVFPmxRxmwb8fosvBPqAr70X+tTThQBOlnQnlAVtjVe/eIfpx3/+EzagLoj+waW6TTuu+fOuJ+iA7ws+zyxY6jtryT2VTKtnh673FIKcFPVIQoUW+53WNsVRWjhI07eKHFqr3jXCCk+4Dvr3rIBirVzuSu6sdfDBGzjyg88wsqamoj05LAWt43dHv0ARZFjoPCrr4f7Encn3MF50hBSBq6OY8LRGUAjD2AIEL/5o/afxrn7eRSO2w76u2ynsa0+tGYtEEVj48VQ+4rJjf29Mnl3/ekVOlK2sfL/tm5ENjqsWQa82FBAy5N1qXQfkMo4=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-registry
      namespace: school-dev
    type: kubernetes.io/dockerconfigjson
