---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-registry
  namespace: school-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBBt5bn3vhdDLhoQFlL0k7qSVkPMf80QaJKVzxBZVqUz4moK2myR2WkooGL5kKW+lSwNi5Nnc30XhMVzUhRUiHcRjT6Wpy85CMKFDZFZJXDTNOwptdNrcVCZryiHavWiBE+BZc+9iQ+ehJxGPb1KZUuKg+m5fJtEPx/JCtzR2KEoJ0/IIVlPfhbRkUuDv6kDD/tJh++dwtMPj/L5DRRzzV/b/THKbNxz0fqEkt/H7uDDlRt1S7BQFj54KqCO5+seFXYpMCfD/fEc8Eys43QLwpuD6uwZCN6/uWjbJd5mOCPsdhCts9AZ52sxSIKYK/BrrEXDZL4r6aLBxLKE8o05OlluRqRrDwNQR7JhF7rLzYwQWsqnNhgZCgBG19Yl7ATtZ67OG61NvcXVvZwFOJ0Lwd8stbyLmVnARjUqCVr9oS4h8GwRM/UMrXW7Y8e+gRYSzC2WzTWBAhGjX6Vqotr+Dy+sgsZZzK5CgQeuxbWcd8KIDCSaqmiVOycthXWllzJNJANTL9rppjg3nkqyUmDmDWsClTgYYnX/IeoDr5EKMqoJ6PubqmhwKiC1dfExJ4CaBF3eeqt0Kz/kpJrhqsYfXKcdZF107K8+Oo4Le1oEdr3AVWnoIw2TcMjfUVA4UeND8a1VO2y7X+2lhl+kEiO078Kg9d05Gp0DslNa/5QIAqEflo4O2/zIGi+fBnezj23KqzTrwNl3wZ2dykKEMJsMHw0cx5RxEvTGKqFEvjqFinqlfy95aP9H2SOvJ0HekJA3dVZA+PW6lYcFH7RAuWrdkP7HbafjrNdhQ1CkSSVSbc5nDmm60NQDk7ayn6w48wpeHosOmpoR92/kHl7DiCEAB4YabUwfxfYdX8J4JeXyugcEftBK2B83ekHIpojQRC3gUm8sx8WPTphICVeu5JZL8+/3WjjeMgMNP2ESzH9nuDUWdHF9vOvklvnctNJyIkVPJ519rimz1g=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-registry
      namespace: school-dev
    type: kubernetes.io/dockerconfigjson
