apiVersion: v1
kind: Namespace
metadata:
  name: shared
---
apiVersion: v1
kind: Namespace
metadata:
  name: school-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: school-rec
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner
