---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: school-gitlab-runner-credentials
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-registration-token: AgC+xNUNxrGFE5yPdbaX/SsyOicEtKS/JELwaxT4/sw6NR8TABQaYFJmAbZ8Ym28imTg/zyJtKEAVnsiqhUNMguD+6LUZ6AHeY1669+XzoWymcqQ9BmgDXQdvDysCii5hNny4hXwvvxQluwXKWNxEsf1Ng/YhnIQwB9vLjTCpm1rAA05+aYOfb7CVX6yW+NEH+WwdB7RihjNDq5u0AysSLEmQ3W+1LyYkYy4yZIaHn+qDbJLSN9co8hpDUKq2HYcQmk528oAnDb0W+G/pg4gWH9ldFRYztJlEj52ndbtIG+aa+gtAkcBqDG0uQgrhe5f83GrlcsGNiSxktntlBTsAT8SDog2nKm4NOXeQ34W1T6TokgOfIJxkG3D5ZQivETLTYKRpUC7/Y+YyLS8NhgJCfT4kj3WBYrkRzLRu08EfXAkCtboJ5H24PSj+KwDDjObwa3uV9+qieMDPpUFbLi2H2G7M+i8bMVgoGpYgmKWFnDs5+R56MWAs0fHP5dHXEkgUZwG9CKnkEZFAGtIxMWzgufR8MwTnBXRLxuWMpqIew2TFDEYgEfJuV6bt81lo6ac+IMEtaXKkmmtFXKnLx1tF0Qu7UknsoER3hq9SvcnQR8BktqV5ITq4hj4DnaFGLAehyPZuLqfj0FP3yfX1yjQpPF4zXLs2C1KrHpUN9zv8zuufSOnJ0xRHEAEIqZfvfG2+VCDJ8CUX6MDUuCvrfPAgUl+0hS0vGU5mxwCadTUBA==
    runner-token: AgBOTk+ZDqJEL+pK229OCQfre4HevZ6NLoQdw+hsg3n530Qg21JMHm0KxSNHYKMzw0wvqFH5x/w7VpkxKZBWhRMOHlQ+/3Vz7r1sA/dSFBklL016ar1aQhuY8+gpwG/PViN2xFVlYrCS/JY6vgz2GTcrmz+OyYTihYz6O0wLN0TUcV+j9E9gKbn6mO9IyFrCMBBIe31hugbZJ0WLelFhf3rrYUbolSKW/SPkA6H4oT/0j58nWOmruKkKlchC5wVbbG/EM2i+U9IGH767SGRSlzDIhYrWqJyZ1vND13LakCO1eG/bKyn+NBmBuCpfsVPwKThKrgG1I3sTNijmdGOXqsAe3YfRyk5KMaGFgLm7t2n8ebyAN88mcQEk+VNa6SWH+E1lxm7mFPYFi9r+r2CYNoVbR+Kf7DZMmmzw5k3bSbnbVP40YyDZRaNd3E51DG+SKniXLWT4Hob4+XDztbprlMZ2wsBGYHeNZCAth5UIeJJ2wXiKT46fPcvj/5coG1PKlS7tIwko21rTRwiuy0B7XZVpeO2HNIIJaKWTA8aSI72WTto1PQa6r/gjrF2HNHWzWKO/mRWKgfzsiXF91qoEHv9FK8mfK39QH711mELY1fv+XB3fEKGtBCG+9ycyfw5Vr8zTrRm3mp0NbJeUEVaBsNQRcgj+TPhIfrsbnmkH8lUp8bNf01Ce6fDO43cV1l7DopQ=
  template:
    metadata:
      creationTimestamp: null
      name: school-gitlab-runner-credentials
      namespace: gitlab-runner
