---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: school-gitlab-runner-credentials
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-registration-token: AgCGcjYGjhE0tzrmSvGipxtaU1vpIJ5TP7C25KOi0DW/mwwqoL3vms6EGoRU8/kg558k4JEsH4YcjZQ9dNTnW5bs+PoHEVje3arQAosc9aApyvj9s4QN2JsdxpFesYEfKJvjW8pVVEA+qwvNAgCdCU1YWmz6yj8jAy+tYtjBWLN8aq6lE1Pex/Pz6XiEhO5bzPFubM39fmuPlGmKRbHL8C2Po3ZAtcbDP+OFl31oMI4gjKwDK2wrLwXmO7l5ICyJOYqXIbv4fSyGsdRzQXRGAtQSRKTeiohlNQVYfUFZ0+pJERmBNwcGm+d2ZcEOlqbS66PPbnDAJyqEcZZ16qkbKpV+bNaPcMjdUAiirx/NZrebDTTsJHf6zHwxWvv6XaAWb/WsD8P99Ie3r6Bt3jK2jzWiUX6PJzQmPIgSWDcPDWZcNr3atOxuqy7oxQHLj5sHBupxqT1u6nqwRchHn+1Hvct0St/xDWr6te5ixRWgi8htqBmsiuYe1Cq5FijgDtr52bKOdsPlSUpmD0XeW65njp0bK25RdTJsYeP8I+LKLwXBiI7pfANDxr02WshEvtDRYJKWbVM8X7Ak+BYyL2RVyAFQlI623LjR7DwoAgCEP/poVQM8WR7CQfwaW6CvVcp6zBMKMgg0+nFMlqfrzy0s8DbqmGz+XTbGcC5pQlzH990ecthEYa1PZvYTHSEGVLC+RVY7jd/2RMc8UNQ+G64Beg==
    runner-token: AgCmyM/SdeTfYCpm+9g1ugK2/A+SdFl9v8y73M0ycFfxiU8+ALTPmtO+1F3awJIWS9mkfGHQKvP4EpwQxs1p89fb75LeZe9q/9X8MBMITdiRo/PtQyQe0ae59Fz5UD7wMS7HKY0+pr93C5J3Q4tSYMpt8biBJ6WdrZabWWO8zrfxEAaX0bEbLTLnhq+v7waGgmOP6XzLcsSfVf5HOqgyCF39XsAicNXb0mhT986QlRMhWjHDgw8RRlF5EBZzB9R/UPCFetrIALOzE3X1RXCUyr3FuQ4yKP94evlh7VBc3PzmGI8Mho4bO23SpKfv8RvonxdKnd5QpE4WRAHRjnW5uspoGSgPTL9NG7faNFlQGV17w0ysFHD7jGQlq8Xp8hydDB86sA8S/vQ3j3c+WnnFLBFqxqhp3VWkBrZ+6g9ITqVDRIm3ta01Ovpm3xLv6FyKrf/9bP1ddrTaY13QJBjfCYav16KKElGE0rBZKkzJL/gP/D8aQRuxZxFK4BVdXcVZreNISJZln3Hu0UsN4oAbhgWT8gvKTAnEDp5uK1w1lGUB8qn7cHbgG/2FBwxsuvDuyj1MpCFynG7QZ26CyyL4JhIM6eB/vro5Oc560GexyLrlcOfON5jGfHhgdfl8Efxxkc7tYaSMEFg+yO91Ki3nuRLt4AIkIZvRAsnEqYABuvMvCmWT5Jttf31tR852kWdJki0=
  template:
    metadata:
      creationTimestamp: null
      name: school-gitlab-runner-credentials
      namespace: gitlab-runner
